name: secrets
on: push

jobs:
  get-secrets:
    runs-on: ubuntu-latest
    steps:
    - name: get secrets
      run: echo ${{ secrets.level }} # Settings > Security > Secrets and variables > Actions > Variables > Repository variables 에서 설정
  